name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code (Go)
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Install Go dependencies
        working-directory: ./v1
        run: go mod download

      - name: Build Go
        working-directory: ./v1
        run: go build -v ./...

      - name: Test Go
        working-directory: ./v1
        run: go test -v ./...

      - name: Lint Go code
        working-directory: ./v1
        run: go fmt ./... && go vet ./...

      - name: Build and Push Go Docker image
        working-directory: ./v1
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker build -t kayraberktuncer/portfolion-service:0.1 .
          docker push kayraberktuncer/portfolion-service:0.1

      - name: Checkout code Client
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Client dependencies
        working-directory: ./client
        run: npm ci

      - name: Build Client app
        working-directory: ./client
        run: npm run build

      - name: Build and Push Client Docker image
        working-directory: ./client
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker build -t kayraberktuncer/portfolion-client:0.1 .
          docker push kayraberktuncer/portfolion-client:0.1
