name: Pre-check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20

      - name: Install Go dependencies
        working-directory: ./v1
        run: go mod download

      - name: Build Go
        working-directory: ./v1
        run: go build -v ./...

      - name: Test Go
        working-directory: ./v1
        run: go test -v ./...

      - name: Lint Go code
        working-directory: ./v1
        run: go fmt ./... && go vet ./...

      - name: Build and Push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker build -t kayraberktuncer/portfolion-service:0.1 .
          docker push kayraberktuncer/portfolion-service:0.1

      - name: Checkout code (Next.js)
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install Next.js dependencies
        working-directory: ./client
        run: npm ci

      - name: Build Next.js app
        working-directory: ./client
        run: npm run build
