name: Pre-check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Install Go dependencies
        working-directory: ./v1
        run: go mod download

      - name: Build Go
        working-directory: ./v1
        run: go build -v ./...

      - name: Test Go
        working-directory: ./v1
        run: go test -v ./...

      - name: Lint Go code
        working-directory: ./v1
        run: go fmt ./... && go vet ./...

      - name: Install Docker
        uses: docker/setup-docker@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        working-directory: ./v1
        run: docker build -t kayraberktuncer/portfolion-service:0.1 .

      - name: Push Docker image
        working-directory: ./v1
        run: docker push kayraberktuncer/portfolion-service:0.1

      - name: Checkout code (Next.js)
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Next.js dependencies
        working-directory: ./client
        run: npm ci

      - name: Build Next.js app
        working-directory: ./client
        run: npm run build